package com.gmh.wzz.api.model;

import java.io.Serializable;
import java.util.Date;

public class TbWzzWifi implements Serializable{

	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wzz_wifi.WIFIID
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    private String wifiid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wzz_wifi.USER_ID
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wzz_wifi.WIFI_MAC
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    private String wifiMac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wzz_wifi.WIFI_SSID
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    private String wifiSsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wzz_wifi.WIFI_PROV
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    private String wifiProv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wzz_wifi.WIFI_CITY
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    private String wifiCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wzz_wifi.WIFI_X
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    private String wifiX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wzz_wifi.WIFI_Y
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    private String wifiY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wzz_wifi.WIFI_ADDRESS
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    private String wifiAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wzz_wifi.SHARE_TIME
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    private Date shareTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wzz_wifi.WIFIID
     *
     * @return the value of tb_wzz_wifi.WIFIID
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public String getWifiid() {
        return wifiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wzz_wifi.WIFIID
     *
     * @param wifiid the value for tb_wzz_wifi.WIFIID
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public void setWifiid(String wifiid) {
        this.wifiid = wifiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wzz_wifi.USER_ID
     *
     * @return the value of tb_wzz_wifi.USER_ID
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wzz_wifi.USER_ID
     *
     * @param userId the value for tb_wzz_wifi.USER_ID
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wzz_wifi.WIFI_MAC
     *
     * @return the value of tb_wzz_wifi.WIFI_MAC
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public String getWifiMac() {
        return wifiMac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wzz_wifi.WIFI_MAC
     *
     * @param wifiMac the value for tb_wzz_wifi.WIFI_MAC
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public void setWifiMac(String wifiMac) {
        this.wifiMac = wifiMac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wzz_wifi.WIFI_SSID
     *
     * @return the value of tb_wzz_wifi.WIFI_SSID
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public String getWifiSsid() {
        return wifiSsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wzz_wifi.WIFI_SSID
     *
     * @param wifiSsid the value for tb_wzz_wifi.WIFI_SSID
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public void setWifiSsid(String wifiSsid) {
        this.wifiSsid = wifiSsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wzz_wifi.WIFI_PROV
     *
     * @return the value of tb_wzz_wifi.WIFI_PROV
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public String getWifiProv() {
        return wifiProv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wzz_wifi.WIFI_PROV
     *
     * @param wifiProv the value for tb_wzz_wifi.WIFI_PROV
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public void setWifiProv(String wifiProv) {
        this.wifiProv = wifiProv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wzz_wifi.WIFI_CITY
     *
     * @return the value of tb_wzz_wifi.WIFI_CITY
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public String getWifiCity() {
        return wifiCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wzz_wifi.WIFI_CITY
     *
     * @param wifiCity the value for tb_wzz_wifi.WIFI_CITY
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public void setWifiCity(String wifiCity) {
        this.wifiCity = wifiCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wzz_wifi.WIFI_X
     *
     * @return the value of tb_wzz_wifi.WIFI_X
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public String getWifiX() {
        return wifiX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wzz_wifi.WIFI_X
     *
     * @param wifiX the value for tb_wzz_wifi.WIFI_X
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public void setWifiX(String wifiX) {
        this.wifiX = wifiX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wzz_wifi.WIFI_Y
     *
     * @return the value of tb_wzz_wifi.WIFI_Y
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public String getWifiY() {
        return wifiY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wzz_wifi.WIFI_Y
     *
     * @param wifiY the value for tb_wzz_wifi.WIFI_Y
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public void setWifiY(String wifiY) {
        this.wifiY = wifiY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wzz_wifi.WIFI_ADDRESS
     *
     * @return the value of tb_wzz_wifi.WIFI_ADDRESS
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public String getWifiAddress() {
        return wifiAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wzz_wifi.WIFI_ADDRESS
     *
     * @param wifiAddress the value for tb_wzz_wifi.WIFI_ADDRESS
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public void setWifiAddress(String wifiAddress) {
        this.wifiAddress = wifiAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wzz_wifi.SHARE_TIME
     *
     * @return the value of tb_wzz_wifi.SHARE_TIME
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public Date getShareTime() {
        return shareTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wzz_wifi.SHARE_TIME
     *
     * @param shareTime the value for tb_wzz_wifi.SHARE_TIME
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public void setShareTime(Date shareTime) {
        this.shareTime = shareTime;
    }
}