package com.gmh.wzz.api.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbWzzWifiExample implements Serializable{

	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_wzz_wifi
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_wzz_wifi
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_wzz_wifi
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_wifi
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public TbWzzWifiExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_wifi
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_wifi
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_wifi
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_wifi
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_wifi
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_wifi
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_wifi
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_wifi
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_wifi
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_wifi
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_wzz_wifi
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWifiidIsNull() {
            addCriterion("WIFIID is null");
            return (Criteria) this;
        }

        public Criteria andWifiidIsNotNull() {
            addCriterion("WIFIID is not null");
            return (Criteria) this;
        }

        public Criteria andWifiidEqualTo(String value) {
            addCriterion("WIFIID =", value, "wifiid");
            return (Criteria) this;
        }

        public Criteria andWifiidNotEqualTo(String value) {
            addCriterion("WIFIID <>", value, "wifiid");
            return (Criteria) this;
        }

        public Criteria andWifiidGreaterThan(String value) {
            addCriterion("WIFIID >", value, "wifiid");
            return (Criteria) this;
        }

        public Criteria andWifiidGreaterThanOrEqualTo(String value) {
            addCriterion("WIFIID >=", value, "wifiid");
            return (Criteria) this;
        }

        public Criteria andWifiidLessThan(String value) {
            addCriterion("WIFIID <", value, "wifiid");
            return (Criteria) this;
        }

        public Criteria andWifiidLessThanOrEqualTo(String value) {
            addCriterion("WIFIID <=", value, "wifiid");
            return (Criteria) this;
        }

        public Criteria andWifiidLike(String value) {
            addCriterion("WIFIID like", value, "wifiid");
            return (Criteria) this;
        }

        public Criteria andWifiidNotLike(String value) {
            addCriterion("WIFIID not like", value, "wifiid");
            return (Criteria) this;
        }

        public Criteria andWifiidIn(List<String> values) {
            addCriterion("WIFIID in", values, "wifiid");
            return (Criteria) this;
        }

        public Criteria andWifiidNotIn(List<String> values) {
            addCriterion("WIFIID not in", values, "wifiid");
            return (Criteria) this;
        }

        public Criteria andWifiidBetween(String value1, String value2) {
            addCriterion("WIFIID between", value1, value2, "wifiid");
            return (Criteria) this;
        }

        public Criteria andWifiidNotBetween(String value1, String value2) {
            addCriterion("WIFIID not between", value1, value2, "wifiid");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("USER_ID like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("USER_ID not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andWifiMacIsNull() {
            addCriterion("WIFI_MAC is null");
            return (Criteria) this;
        }

        public Criteria andWifiMacIsNotNull() {
            addCriterion("WIFI_MAC is not null");
            return (Criteria) this;
        }

        public Criteria andWifiMacEqualTo(String value) {
            addCriterion("WIFI_MAC =", value, "wifiMac");
            return (Criteria) this;
        }

        public Criteria andWifiMacNotEqualTo(String value) {
            addCriterion("WIFI_MAC <>", value, "wifiMac");
            return (Criteria) this;
        }

        public Criteria andWifiMacGreaterThan(String value) {
            addCriterion("WIFI_MAC >", value, "wifiMac");
            return (Criteria) this;
        }

        public Criteria andWifiMacGreaterThanOrEqualTo(String value) {
            addCriterion("WIFI_MAC >=", value, "wifiMac");
            return (Criteria) this;
        }

        public Criteria andWifiMacLessThan(String value) {
            addCriterion("WIFI_MAC <", value, "wifiMac");
            return (Criteria) this;
        }

        public Criteria andWifiMacLessThanOrEqualTo(String value) {
            addCriterion("WIFI_MAC <=", value, "wifiMac");
            return (Criteria) this;
        }

        public Criteria andWifiMacLike(String value) {
            addCriterion("WIFI_MAC like", value, "wifiMac");
            return (Criteria) this;
        }

        public Criteria andWifiMacNotLike(String value) {
            addCriterion("WIFI_MAC not like", value, "wifiMac");
            return (Criteria) this;
        }

        public Criteria andWifiMacIn(List<String> values) {
            addCriterion("WIFI_MAC in", values, "wifiMac");
            return (Criteria) this;
        }

        public Criteria andWifiMacNotIn(List<String> values) {
            addCriterion("WIFI_MAC not in", values, "wifiMac");
            return (Criteria) this;
        }

        public Criteria andWifiMacBetween(String value1, String value2) {
            addCriterion("WIFI_MAC between", value1, value2, "wifiMac");
            return (Criteria) this;
        }

        public Criteria andWifiMacNotBetween(String value1, String value2) {
            addCriterion("WIFI_MAC not between", value1, value2, "wifiMac");
            return (Criteria) this;
        }

        public Criteria andWifiSsidIsNull() {
            addCriterion("WIFI_SSID is null");
            return (Criteria) this;
        }

        public Criteria andWifiSsidIsNotNull() {
            addCriterion("WIFI_SSID is not null");
            return (Criteria) this;
        }

        public Criteria andWifiSsidEqualTo(String value) {
            addCriterion("WIFI_SSID =", value, "wifiSsid");
            return (Criteria) this;
        }

        public Criteria andWifiSsidNotEqualTo(String value) {
            addCriterion("WIFI_SSID <>", value, "wifiSsid");
            return (Criteria) this;
        }

        public Criteria andWifiSsidGreaterThan(String value) {
            addCriterion("WIFI_SSID >", value, "wifiSsid");
            return (Criteria) this;
        }

        public Criteria andWifiSsidGreaterThanOrEqualTo(String value) {
            addCriterion("WIFI_SSID >=", value, "wifiSsid");
            return (Criteria) this;
        }

        public Criteria andWifiSsidLessThan(String value) {
            addCriterion("WIFI_SSID <", value, "wifiSsid");
            return (Criteria) this;
        }

        public Criteria andWifiSsidLessThanOrEqualTo(String value) {
            addCriterion("WIFI_SSID <=", value, "wifiSsid");
            return (Criteria) this;
        }

        public Criteria andWifiSsidLike(String value) {
            addCriterion("WIFI_SSID like", value, "wifiSsid");
            return (Criteria) this;
        }

        public Criteria andWifiSsidNotLike(String value) {
            addCriterion("WIFI_SSID not like", value, "wifiSsid");
            return (Criteria) this;
        }

        public Criteria andWifiSsidIn(List<String> values) {
            addCriterion("WIFI_SSID in", values, "wifiSsid");
            return (Criteria) this;
        }

        public Criteria andWifiSsidNotIn(List<String> values) {
            addCriterion("WIFI_SSID not in", values, "wifiSsid");
            return (Criteria) this;
        }

        public Criteria andWifiSsidBetween(String value1, String value2) {
            addCriterion("WIFI_SSID between", value1, value2, "wifiSsid");
            return (Criteria) this;
        }

        public Criteria andWifiSsidNotBetween(String value1, String value2) {
            addCriterion("WIFI_SSID not between", value1, value2, "wifiSsid");
            return (Criteria) this;
        }

        public Criteria andWifiProvIsNull() {
            addCriterion("WIFI_PROV is null");
            return (Criteria) this;
        }

        public Criteria andWifiProvIsNotNull() {
            addCriterion("WIFI_PROV is not null");
            return (Criteria) this;
        }

        public Criteria andWifiProvEqualTo(String value) {
            addCriterion("WIFI_PROV =", value, "wifiProv");
            return (Criteria) this;
        }

        public Criteria andWifiProvNotEqualTo(String value) {
            addCriterion("WIFI_PROV <>", value, "wifiProv");
            return (Criteria) this;
        }

        public Criteria andWifiProvGreaterThan(String value) {
            addCriterion("WIFI_PROV >", value, "wifiProv");
            return (Criteria) this;
        }

        public Criteria andWifiProvGreaterThanOrEqualTo(String value) {
            addCriterion("WIFI_PROV >=", value, "wifiProv");
            return (Criteria) this;
        }

        public Criteria andWifiProvLessThan(String value) {
            addCriterion("WIFI_PROV <", value, "wifiProv");
            return (Criteria) this;
        }

        public Criteria andWifiProvLessThanOrEqualTo(String value) {
            addCriterion("WIFI_PROV <=", value, "wifiProv");
            return (Criteria) this;
        }

        public Criteria andWifiProvLike(String value) {
            addCriterion("WIFI_PROV like", value, "wifiProv");
            return (Criteria) this;
        }

        public Criteria andWifiProvNotLike(String value) {
            addCriterion("WIFI_PROV not like", value, "wifiProv");
            return (Criteria) this;
        }

        public Criteria andWifiProvIn(List<String> values) {
            addCriterion("WIFI_PROV in", values, "wifiProv");
            return (Criteria) this;
        }

        public Criteria andWifiProvNotIn(List<String> values) {
            addCriterion("WIFI_PROV not in", values, "wifiProv");
            return (Criteria) this;
        }

        public Criteria andWifiProvBetween(String value1, String value2) {
            addCriterion("WIFI_PROV between", value1, value2, "wifiProv");
            return (Criteria) this;
        }

        public Criteria andWifiProvNotBetween(String value1, String value2) {
            addCriterion("WIFI_PROV not between", value1, value2, "wifiProv");
            return (Criteria) this;
        }

        public Criteria andWifiCityIsNull() {
            addCriterion("WIFI_CITY is null");
            return (Criteria) this;
        }

        public Criteria andWifiCityIsNotNull() {
            addCriterion("WIFI_CITY is not null");
            return (Criteria) this;
        }

        public Criteria andWifiCityEqualTo(String value) {
            addCriterion("WIFI_CITY =", value, "wifiCity");
            return (Criteria) this;
        }

        public Criteria andWifiCityNotEqualTo(String value) {
            addCriterion("WIFI_CITY <>", value, "wifiCity");
            return (Criteria) this;
        }

        public Criteria andWifiCityGreaterThan(String value) {
            addCriterion("WIFI_CITY >", value, "wifiCity");
            return (Criteria) this;
        }

        public Criteria andWifiCityGreaterThanOrEqualTo(String value) {
            addCriterion("WIFI_CITY >=", value, "wifiCity");
            return (Criteria) this;
        }

        public Criteria andWifiCityLessThan(String value) {
            addCriterion("WIFI_CITY <", value, "wifiCity");
            return (Criteria) this;
        }

        public Criteria andWifiCityLessThanOrEqualTo(String value) {
            addCriterion("WIFI_CITY <=", value, "wifiCity");
            return (Criteria) this;
        }

        public Criteria andWifiCityLike(String value) {
            addCriterion("WIFI_CITY like", value, "wifiCity");
            return (Criteria) this;
        }

        public Criteria andWifiCityNotLike(String value) {
            addCriterion("WIFI_CITY not like", value, "wifiCity");
            return (Criteria) this;
        }

        public Criteria andWifiCityIn(List<String> values) {
            addCriterion("WIFI_CITY in", values, "wifiCity");
            return (Criteria) this;
        }

        public Criteria andWifiCityNotIn(List<String> values) {
            addCriterion("WIFI_CITY not in", values, "wifiCity");
            return (Criteria) this;
        }

        public Criteria andWifiCityBetween(String value1, String value2) {
            addCriterion("WIFI_CITY between", value1, value2, "wifiCity");
            return (Criteria) this;
        }

        public Criteria andWifiCityNotBetween(String value1, String value2) {
            addCriterion("WIFI_CITY not between", value1, value2, "wifiCity");
            return (Criteria) this;
        }

        public Criteria andWifiXIsNull() {
            addCriterion("WIFI_X is null");
            return (Criteria) this;
        }

        public Criteria andWifiXIsNotNull() {
            addCriterion("WIFI_X is not null");
            return (Criteria) this;
        }

        public Criteria andWifiXEqualTo(String value) {
            addCriterion("WIFI_X =", value, "wifiX");
            return (Criteria) this;
        }

        public Criteria andWifiXNotEqualTo(String value) {
            addCriterion("WIFI_X <>", value, "wifiX");
            return (Criteria) this;
        }

        public Criteria andWifiXGreaterThan(String value) {
            addCriterion("WIFI_X >", value, "wifiX");
            return (Criteria) this;
        }

        public Criteria andWifiXGreaterThanOrEqualTo(String value) {
            addCriterion("WIFI_X >=", value, "wifiX");
            return (Criteria) this;
        }

        public Criteria andWifiXLessThan(String value) {
            addCriterion("WIFI_X <", value, "wifiX");
            return (Criteria) this;
        }

        public Criteria andWifiXLessThanOrEqualTo(String value) {
            addCriterion("WIFI_X <=", value, "wifiX");
            return (Criteria) this;
        }

        public Criteria andWifiXLike(String value) {
            addCriterion("WIFI_X like", value, "wifiX");
            return (Criteria) this;
        }

        public Criteria andWifiXNotLike(String value) {
            addCriterion("WIFI_X not like", value, "wifiX");
            return (Criteria) this;
        }

        public Criteria andWifiXIn(List<String> values) {
            addCriterion("WIFI_X in", values, "wifiX");
            return (Criteria) this;
        }

        public Criteria andWifiXNotIn(List<String> values) {
            addCriterion("WIFI_X not in", values, "wifiX");
            return (Criteria) this;
        }

        public Criteria andWifiXBetween(String value1, String value2) {
            addCriterion("WIFI_X between", value1, value2, "wifiX");
            return (Criteria) this;
        }

        public Criteria andWifiXNotBetween(String value1, String value2) {
            addCriterion("WIFI_X not between", value1, value2, "wifiX");
            return (Criteria) this;
        }

        public Criteria andWifiYIsNull() {
            addCriterion("WIFI_Y is null");
            return (Criteria) this;
        }

        public Criteria andWifiYIsNotNull() {
            addCriterion("WIFI_Y is not null");
            return (Criteria) this;
        }

        public Criteria andWifiYEqualTo(String value) {
            addCriterion("WIFI_Y =", value, "wifiY");
            return (Criteria) this;
        }

        public Criteria andWifiYNotEqualTo(String value) {
            addCriterion("WIFI_Y <>", value, "wifiY");
            return (Criteria) this;
        }

        public Criteria andWifiYGreaterThan(String value) {
            addCriterion("WIFI_Y >", value, "wifiY");
            return (Criteria) this;
        }

        public Criteria andWifiYGreaterThanOrEqualTo(String value) {
            addCriterion("WIFI_Y >=", value, "wifiY");
            return (Criteria) this;
        }

        public Criteria andWifiYLessThan(String value) {
            addCriterion("WIFI_Y <", value, "wifiY");
            return (Criteria) this;
        }

        public Criteria andWifiYLessThanOrEqualTo(String value) {
            addCriterion("WIFI_Y <=", value, "wifiY");
            return (Criteria) this;
        }

        public Criteria andWifiYLike(String value) {
            addCriterion("WIFI_Y like", value, "wifiY");
            return (Criteria) this;
        }

        public Criteria andWifiYNotLike(String value) {
            addCriterion("WIFI_Y not like", value, "wifiY");
            return (Criteria) this;
        }

        public Criteria andWifiYIn(List<String> values) {
            addCriterion("WIFI_Y in", values, "wifiY");
            return (Criteria) this;
        }

        public Criteria andWifiYNotIn(List<String> values) {
            addCriterion("WIFI_Y not in", values, "wifiY");
            return (Criteria) this;
        }

        public Criteria andWifiYBetween(String value1, String value2) {
            addCriterion("WIFI_Y between", value1, value2, "wifiY");
            return (Criteria) this;
        }

        public Criteria andWifiYNotBetween(String value1, String value2) {
            addCriterion("WIFI_Y not between", value1, value2, "wifiY");
            return (Criteria) this;
        }

        public Criteria andWifiAddressIsNull() {
            addCriterion("WIFI_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andWifiAddressIsNotNull() {
            addCriterion("WIFI_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andWifiAddressEqualTo(String value) {
            addCriterion("WIFI_ADDRESS =", value, "wifiAddress");
            return (Criteria) this;
        }

        public Criteria andWifiAddressNotEqualTo(String value) {
            addCriterion("WIFI_ADDRESS <>", value, "wifiAddress");
            return (Criteria) this;
        }

        public Criteria andWifiAddressGreaterThan(String value) {
            addCriterion("WIFI_ADDRESS >", value, "wifiAddress");
            return (Criteria) this;
        }

        public Criteria andWifiAddressGreaterThanOrEqualTo(String value) {
            addCriterion("WIFI_ADDRESS >=", value, "wifiAddress");
            return (Criteria) this;
        }

        public Criteria andWifiAddressLessThan(String value) {
            addCriterion("WIFI_ADDRESS <", value, "wifiAddress");
            return (Criteria) this;
        }

        public Criteria andWifiAddressLessThanOrEqualTo(String value) {
            addCriterion("WIFI_ADDRESS <=", value, "wifiAddress");
            return (Criteria) this;
        }

        public Criteria andWifiAddressLike(String value) {
            addCriterion("WIFI_ADDRESS like", value, "wifiAddress");
            return (Criteria) this;
        }

        public Criteria andWifiAddressNotLike(String value) {
            addCriterion("WIFI_ADDRESS not like", value, "wifiAddress");
            return (Criteria) this;
        }

        public Criteria andWifiAddressIn(List<String> values) {
            addCriterion("WIFI_ADDRESS in", values, "wifiAddress");
            return (Criteria) this;
        }

        public Criteria andWifiAddressNotIn(List<String> values) {
            addCriterion("WIFI_ADDRESS not in", values, "wifiAddress");
            return (Criteria) this;
        }

        public Criteria andWifiAddressBetween(String value1, String value2) {
            addCriterion("WIFI_ADDRESS between", value1, value2, "wifiAddress");
            return (Criteria) this;
        }

        public Criteria andWifiAddressNotBetween(String value1, String value2) {
            addCriterion("WIFI_ADDRESS not between", value1, value2, "wifiAddress");
            return (Criteria) this;
        }

        public Criteria andShareTimeIsNull() {
            addCriterion("SHARE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andShareTimeIsNotNull() {
            addCriterion("SHARE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andShareTimeEqualTo(Date value) {
            addCriterion("SHARE_TIME =", value, "shareTime");
            return (Criteria) this;
        }

        public Criteria andShareTimeNotEqualTo(Date value) {
            addCriterion("SHARE_TIME <>", value, "shareTime");
            return (Criteria) this;
        }

        public Criteria andShareTimeGreaterThan(Date value) {
            addCriterion("SHARE_TIME >", value, "shareTime");
            return (Criteria) this;
        }

        public Criteria andShareTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SHARE_TIME >=", value, "shareTime");
            return (Criteria) this;
        }

        public Criteria andShareTimeLessThan(Date value) {
            addCriterion("SHARE_TIME <", value, "shareTime");
            return (Criteria) this;
        }

        public Criteria andShareTimeLessThanOrEqualTo(Date value) {
            addCriterion("SHARE_TIME <=", value, "shareTime");
            return (Criteria) this;
        }

        public Criteria andShareTimeIn(List<Date> values) {
            addCriterion("SHARE_TIME in", values, "shareTime");
            return (Criteria) this;
        }

        public Criteria andShareTimeNotIn(List<Date> values) {
            addCriterion("SHARE_TIME not in", values, "shareTime");
            return (Criteria) this;
        }

        public Criteria andShareTimeBetween(Date value1, Date value2) {
            addCriterion("SHARE_TIME between", value1, value2, "shareTime");
            return (Criteria) this;
        }

        public Criteria andShareTimeNotBetween(Date value1, Date value2) {
            addCriterion("SHARE_TIME not between", value1, value2, "shareTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_wzz_wifi
     *
     * @mbggenerated do_not_delete_during_merge Sat Jun 27 09:02:03 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_wzz_wifi
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}