package com.gmh.wzz.api.model;

import java.io.Serializable;
import java.util.Date;

public class TbWzzInfo implements Serializable{

	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wzz_info.ID
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wzz_info.USER_ID
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wzz_info.TYPE_ID
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    private String typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wzz_info.INFO_TITILE
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    private String infoTitile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wzz_info.INFO_CONTEXT
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    private String infoContext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wzz_info.INFO_PIC
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    private String infoPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wzz_info.INFO_ADDRESS
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    private String infoAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wzz_info.INFO_PHONE
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    private String infoPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wzz_info.INFO_STATUS
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    private String infoStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wzz_info.INFO_TIME
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    private Date infoTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wzz_info.ID
     *
     * @return the value of tb_wzz_info.ID
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wzz_info.ID
     *
     * @param id the value for tb_wzz_info.ID
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wzz_info.USER_ID
     *
     * @return the value of tb_wzz_info.USER_ID
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wzz_info.USER_ID
     *
     * @param userId the value for tb_wzz_info.USER_ID
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wzz_info.TYPE_ID
     *
     * @return the value of tb_wzz_info.TYPE_ID
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wzz_info.TYPE_ID
     *
     * @param typeId the value for tb_wzz_info.TYPE_ID
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wzz_info.INFO_TITILE
     *
     * @return the value of tb_wzz_info.INFO_TITILE
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public String getInfoTitile() {
        return infoTitile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wzz_info.INFO_TITILE
     *
     * @param infoTitile the value for tb_wzz_info.INFO_TITILE
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public void setInfoTitile(String infoTitile) {
        this.infoTitile = infoTitile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wzz_info.INFO_CONTEXT
     *
     * @return the value of tb_wzz_info.INFO_CONTEXT
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public String getInfoContext() {
        return infoContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wzz_info.INFO_CONTEXT
     *
     * @param infoContext the value for tb_wzz_info.INFO_CONTEXT
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public void setInfoContext(String infoContext) {
        this.infoContext = infoContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wzz_info.INFO_PIC
     *
     * @return the value of tb_wzz_info.INFO_PIC
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public String getInfoPic() {
        return infoPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wzz_info.INFO_PIC
     *
     * @param infoPic the value for tb_wzz_info.INFO_PIC
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public void setInfoPic(String infoPic) {
        this.infoPic = infoPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wzz_info.INFO_ADDRESS
     *
     * @return the value of tb_wzz_info.INFO_ADDRESS
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public String getInfoAddress() {
        return infoAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wzz_info.INFO_ADDRESS
     *
     * @param infoAddress the value for tb_wzz_info.INFO_ADDRESS
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public void setInfoAddress(String infoAddress) {
        this.infoAddress = infoAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wzz_info.INFO_PHONE
     *
     * @return the value of tb_wzz_info.INFO_PHONE
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public String getInfoPhone() {
        return infoPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wzz_info.INFO_PHONE
     *
     * @param infoPhone the value for tb_wzz_info.INFO_PHONE
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public void setInfoPhone(String infoPhone) {
        this.infoPhone = infoPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wzz_info.INFO_STATUS
     *
     * @return the value of tb_wzz_info.INFO_STATUS
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public String getInfoStatus() {
        return infoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wzz_info.INFO_STATUS
     *
     * @param infoStatus the value for tb_wzz_info.INFO_STATUS
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public void setInfoStatus(String infoStatus) {
        this.infoStatus = infoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wzz_info.INFO_TIME
     *
     * @return the value of tb_wzz_info.INFO_TIME
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public Date getInfoTime() {
        return infoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wzz_info.INFO_TIME
     *
     * @param infoTime the value for tb_wzz_info.INFO_TIME
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public void setInfoTime(Date infoTime) {
        this.infoTime = infoTime;
    }
}