package com.gmh.wzz.api.model;

import java.io.Serializable;

public class TbWzzUserStore implements Serializable{

	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wzz_user_store.ID
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wzz_user_store.STORE_NAME
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    private String storeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wzz_user_store.TYPE_ID
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    private String typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wzz_user_store.STORE_AREA
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    private String storeArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wzz_user_store.STORE_ADDRESS
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    private String storeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wzz_user_store.STORE_PHONE
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    private String storePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wzz_user_store.STORE_REMARK
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    private String storeRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wzz_user_store.STORE_PIC
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    private String storePic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wzz_user_store.ID
     *
     * @return the value of tb_wzz_user_store.ID
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wzz_user_store.ID
     *
     * @param id the value for tb_wzz_user_store.ID
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wzz_user_store.STORE_NAME
     *
     * @return the value of tb_wzz_user_store.STORE_NAME
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wzz_user_store.STORE_NAME
     *
     * @param storeName the value for tb_wzz_user_store.STORE_NAME
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wzz_user_store.TYPE_ID
     *
     * @return the value of tb_wzz_user_store.TYPE_ID
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wzz_user_store.TYPE_ID
     *
     * @param typeId the value for tb_wzz_user_store.TYPE_ID
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wzz_user_store.STORE_AREA
     *
     * @return the value of tb_wzz_user_store.STORE_AREA
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public String getStoreArea() {
        return storeArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wzz_user_store.STORE_AREA
     *
     * @param storeArea the value for tb_wzz_user_store.STORE_AREA
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public void setStoreArea(String storeArea) {
        this.storeArea = storeArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wzz_user_store.STORE_ADDRESS
     *
     * @return the value of tb_wzz_user_store.STORE_ADDRESS
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public String getStoreAddress() {
        return storeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wzz_user_store.STORE_ADDRESS
     *
     * @param storeAddress the value for tb_wzz_user_store.STORE_ADDRESS
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public void setStoreAddress(String storeAddress) {
        this.storeAddress = storeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wzz_user_store.STORE_PHONE
     *
     * @return the value of tb_wzz_user_store.STORE_PHONE
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public String getStorePhone() {
        return storePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wzz_user_store.STORE_PHONE
     *
     * @param storePhone the value for tb_wzz_user_store.STORE_PHONE
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public void setStorePhone(String storePhone) {
        this.storePhone = storePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wzz_user_store.STORE_REMARK
     *
     * @return the value of tb_wzz_user_store.STORE_REMARK
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public String getStoreRemark() {
        return storeRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wzz_user_store.STORE_REMARK
     *
     * @param storeRemark the value for tb_wzz_user_store.STORE_REMARK
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public void setStoreRemark(String storeRemark) {
        this.storeRemark = storeRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wzz_user_store.STORE_PIC
     *
     * @return the value of tb_wzz_user_store.STORE_PIC
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public String getStorePic() {
        return storePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wzz_user_store.STORE_PIC
     *
     * @param storePic the value for tb_wzz_user_store.STORE_PIC
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    public void setStorePic(String storePic) {
        this.storePic = storePic;
    }
}