package com.gmh.wzz.core.dao;

import com.gmh.wzz.api.model.TbWzzWifi;
import com.gmh.wzz.api.model.TbWzzWifiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbWzzWifiDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_wifi
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    int countByExample(TbWzzWifiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_wifi
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    int deleteByExample(TbWzzWifiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_wifi
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    int deleteByPrimaryKey(String wifiid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_wifi
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    int insert(TbWzzWifi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_wifi
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    int insertSelective(TbWzzWifi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_wifi
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    List<TbWzzWifi> selectByExample(TbWzzWifiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_wifi
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    TbWzzWifi selectByPrimaryKey(String wifiid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_wifi
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    int updateByExampleSelective(@Param("record") TbWzzWifi record, @Param("example") TbWzzWifiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_wifi
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    int updateByExample(@Param("record") TbWzzWifi record, @Param("example") TbWzzWifiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_wifi
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    int updateByPrimaryKeySelective(TbWzzWifi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_wifi
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    int updateByPrimaryKey(TbWzzWifi record);
}