package com.gmh.wzz.core.dao;

import com.gmh.wzz.api.model.TbWzzInfoType;
import com.gmh.wzz.api.model.TbWzzInfoTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbWzzInfoTypeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_info_type
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    int countByExample(TbWzzInfoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_info_type
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    int deleteByExample(TbWzzInfoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_info_type
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_info_type
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    int insert(TbWzzInfoType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_info_type
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    int insertSelective(TbWzzInfoType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_info_type
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    List<TbWzzInfoType> selectByExample(TbWzzInfoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_info_type
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    TbWzzInfoType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_info_type
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    int updateByExampleSelective(@Param("record") TbWzzInfoType record, @Param("example") TbWzzInfoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_info_type
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    int updateByExample(@Param("record") TbWzzInfoType record, @Param("example") TbWzzInfoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_info_type
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    int updateByPrimaryKeySelective(TbWzzInfoType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_info_type
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    int updateByPrimaryKey(TbWzzInfoType record);
}