package com.gmh.wzz.core.dao;

import com.gmh.wzz.api.model.TbWzzUserStore;
import com.gmh.wzz.api.model.TbWzzUserStoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbWzzUserStoreDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_user_store
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    int countByExample(TbWzzUserStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_user_store
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    int deleteByExample(TbWzzUserStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_user_store
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_user_store
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    int insert(TbWzzUserStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_user_store
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    int insertSelective(TbWzzUserStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_user_store
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    List<TbWzzUserStore> selectByExample(TbWzzUserStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_user_store
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    TbWzzUserStore selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_user_store
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    int updateByExampleSelective(@Param("record") TbWzzUserStore record, @Param("example") TbWzzUserStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_user_store
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    int updateByExample(@Param("record") TbWzzUserStore record, @Param("example") TbWzzUserStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_user_store
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    int updateByPrimaryKeySelective(TbWzzUserStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wzz_user_store
     *
     * @mbggenerated Sat Jun 27 09:02:03 CST 2015
     */
    int updateByPrimaryKey(TbWzzUserStore record);
}